// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxxohhzxtkreuvsxkwfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4eG9oaHp4dGtyZXV2c3hrd2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTU2NTAsImV4cCI6MjA2ODI3MTY1MH0.5GPcfthBO615DchSAQHRrAiZZ_TvEFGpzNLWoBnbq00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});