name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main  # Or use your default branch name here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Create gh-pages branch and deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Path to the build output folder
          publish_branch: gh-pages  # This will create the branch if it doesn't exist
